
["PMMO Spellbooks Compat Configs"]

	["PMMO Spellbooks Compat Configs"."Heal XP Configs"]
		#When a spell heals the caster this skill is rewarded. Default: magic
		"Heal Self Skill" = "magic"
		#
		#XP awarded to the caster of when a spell heals themselves.
		#XP given is the amount healed multiplied by this number.
		#If you heal a player for 4 life and this is 10 then you would be rewarded with 10*4=40 xp.
		#Set to 0 to award no experience for healing yourself.
		#Range: > 0
		"Heal Self Xp Reward" = 20
		#
		#When a spell heals another entity this skill is rewarded to the caster. Default: magic
		"Heal Other Skill" = "magic"
		#
		#XP awarded to the caster of a spell that heals another player.
		#XP given is the amount healed multiplied by this number.
		#If you heal a player for 4 life and this is 10 then you would be rewarded with 10*4=40 xp.
		#Set to 0 to award no experience for healing another player.
		#Range: > 0
		"Heal Other Xp Reward" = 20

	["PMMO Spellbooks Compat Configs"."Damage XP Configs"]
		#When a spell damages the caster this skill is rewarded. Default: magic
		"Damage Self Skill" = "magic"
		#
		#XP awarded to the caster of when a spell damages themselves.
		#XP given is the amount dealt multiplied by this number.
		#If you deal 4 damage and this is 10 then you would be rewarded with 10*4=40 xp.
		#Set to 0 to award no experience for damaging yourself.
		#Range: > 0
		"Damage Self Xp Reward" = 0
		#
		#When a spell damages another entity this skill is rewarded to the caster. Default: magic
		"Damage Other Skill" = "magic|combat"
		#
		#XP awarded to the caster of a spell that damages another player.
		#XP given is the amount dealt multiplied by this number.
		#If you deal 4 damage and this is 10 then you would be rewarded with 10*4=40 xp.
		#Set to 0 to award no experience for damaging another player.
		#Range: > 0
		"Damage Other Xp Reward" = 20

